In [50]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
SRC_DIR = PROJECT_ROOT / "src"

sys.path.insert(0, str(SRC_DIR))

In [2]:
import pandas as pd
import numpy as np

train_source1=pd.read_csv('train_source1.csv', sep='\t')

ModuleNotFoundError: No module named 'pandas'

In [3]:
%pip install pandas numpy

Collecting pandas
  Using cached pandas-3.0.6-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Using cached numpy-2.5.3-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\amazon-ml-2026-entity-resolution\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.4-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in d:\amazon-ml-2026-entity-resolution\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.6-cp313-cp313-win_amd64.whl (9.6 MB)
Using cached numpy-2.5.3-cp313-cp313-win_amd64.whl (12.6 MB)
Using cached tzdata-2026.4-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.5.3 pandas-3.0.6 tzdata-2026.4
Note: you may need to restart the kernel to use updated packages.

In [1]:
from pathlib import Path

TRAIN_DIR = Path("../data/train")
TEST_DIR = Path("../data/test")

print("TRAIN FILES")
for file in TRAIN_DIR.iterdir():
    print(file.name)

print("\nTEST FILES")
for file in TEST_DIR.iterdir():
    print(file.name)

TRAIN FILES
train_ground_truth.tsv
train_source1.tsv
train_source2.tsv
train_source3.tsv

TEST FILES
test_source1.tsv
test_source2.tsv
test_source3.tsv

In [4]:
import pandas as pd
import numpy as np

print (pd.__version__)
print (np.__version__)

3.0.6
2.5.3

In [7]:
train_source1 = pd.read_csv(
    TRAIN_DIR / "train_source1.tsv",
    sep="\t"
)

train_source2 = pd.read_csv(
    TRAIN_DIR / "train_source2.tsv",
    sep="\t"
)

train_source3 = pd.read_csv(
    TRAIN_DIR / "train_source3.tsv",
    sep="\t"
)

In [9]:
print("Source 1:", train_source1.shape)
print("Source 2:", train_source2.shape)
print("Source 3:", train_source3.shape)

Source 1: (2206821, 4)
Source 2: (5034616, 4)
Source 3: (5285603, 4)

In [12]:
train_source3.head()

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India

In [14]:
print("Source 1:", train_source1.info())
print("Source 2:", train_source2.info())
print("Source 3:", train_source3.info())

<class 'pandas.DataFrame'>
RangeIndex: 2206821 entries, 0 to 2206820
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   entity_id         str
 1   business_name     str
 2   business_address  str
 3   country           str
dtypes: str(4)
memory usage: 67.3 MB
Source 1: None
<class 'pandas.DataFrame'>
RangeIndex: 5034616 entries, 0 to 5034615
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   entity_id         str
 1   business_name     str
 2   business_address  str
 3   country           str
dtypes: str(4)
memory usage: 153.6 MB
Source 2: None
<class 'pandas.DataFrame'>
RangeIndex: 5285603 entries, 0 to 5285602
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   entity_id         str
 1   business_name     str
 2   business_address  str
 3   country           str
dtypes: str(4)
memory usage: 161.3 MB
Source 3: None

In [15]:
for name, df in {
    "Source 1": train_source1,
    "Source 2": train_source2,
    "Source 3": train_source3
}.items():
    print(f"\n===== {name} =====")
    print("Shape:", df.shape)
    print("\nData types:")
    print(df.dtypes)
    print("\nMissing values:")
    print(df.isna().sum())
    print("\nDuplicate rows:", df.duplicated().sum())
    print("Duplicate entity IDs:", df["entity_id"].duplicated().sum())

===== Source 1 =====
Shape: (2206821, 4)

Data types:
entity_id           str
business_name       str
business_address    str
country             str
dtype: object

Missing values:
entity_id           0
business_name       0
business_address    0
country             0
dtype: int64

Duplicate rows: 0
Duplicate entity IDs: 0

===== Source 2 =====
Shape: (5034616, 4)

Data types:
entity_id           str
business_name       str
business_address    str
country             str
dtype: object

Missing values:
entity_id                0
business_name            2
business_address    168967
country                  0
dtype: int64

Duplicate rows: 0
Duplicate entity IDs: 0

===== Source 3 =====
Shape: (5285603, 4)

Data types:
entity_id           str
business_name       str
business_address    str
country             str
dtype: object

Missing values:
entity_id                0
business_name           13
business_address    175916
country                  0
dtype: int64

Duplicate rows: 0
Duplicate entity IDs: 0

In [16]:
for name, df in {
    "Source 1": train_source1,
    "Source 2": train_source2,
    "Source 3": train_source3
}.items():
    
    print(f"\n===== {name} =====")
    print(df["country"].value_counts(dropna=False))

===== Source 1 =====
country
US       1323633
India     883188
Name: count, dtype: int64

===== Source 2 =====
country
US       3016817
India    2017799
Name: count, dtype: int64

===== Source 3 =====
country
US       3170056
India    2115547
Name: count, dtype: int64

In [ ]:
#phase 3 starts here 

train_ground_truth = pd.read_csv(
    TRAIN_DIR / "train_ground_truth.tsv",
    sep="\t"
)

In [18]:
print("Shape:", train_ground_truth.shape)
print("\nColumns:")
print(train_ground_truth.columns)

print("\nFirst 5 rows:")
display(train_ground_truth.head())

Shape: (2206821, 2)

Columns:
Index(['source1_entity_id', 'matched_entity_ids'], dtype='str')

First 5 rows:

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [19]:
match_counts = (
    train_ground_truth["matched_entity_ids"]
    .fillna("")
    .apply(
        lambda x: 0 if x.strip() == "" else len(x.split(","))
    )
)

print(match_counts.describe())

count    2.206821e+06
mean     3.461253e+00
std      1.705323e+00
min      0.000000e+00
25%      2.000000e+00
50%      3.000000e+00
75%      5.000000e+00
max      1.100000e+01
Name: matched_entity_ids, dtype: float64

In [20]:
print("\nNumber of matches per Source 1 entity:")
print(match_counts.value_counts().sort_index())

Number of matches per Source 1 entity:
matched_entity_ids
0     123247
1     119157
2     375212
3     530841
4     484115
5     321957
6     164868
7      63968
8      18680
9       4205
10       534
11        37
Name: count, dtype: int64

In [21]:
empty_matches = (
    train_ground_truth["matched_entity_ids"]
    .fillna("")
    .str.strip()
    .eq("")
)

print("No-match Source 1 entities:", empty_matches.sum())
print(
    "Percentage:",
    empty_matches.mean() * 100
)

No-match Source 1 entities: 123247
Percentage: 5.584820880352326

In [22]:
source1_ids = set(train_source1["entity_id"])
source2_ids = set(train_source2["entity_id"])
source3_ids = set(train_source3["entity_id"])

print(
    "Ground-truth S1 IDs missing from Source 1:",
    (~train_ground_truth["source1_entity_id"].isin(source1_ids)).sum()
)

Ground-truth S1 IDs missing from Source 1: 0

In [23]:
source2_ids=set(train_source2["entity_id"])
source3_ids=set(train_source3["entity_id"])

matched_ids=(
    train_ground_truth["source1_entity_id"].fillna("").str.split(",").explode().str.strip()
)

matched_ids=matched_ids[matched_ids != ""]
print("Total matched ID references:", len(matched_ids))
print("Unique matched IDs:", matched_ids.nunique())

invalid_ids = matched_ids[
    ~matched_ids.isin(source2_ids | source3_ids)
]

print("Matched IDs not found in Source 2 or Source 3:", len(invalid_ids))

Total matched ID references: 2206821
Unique matched IDs: 2206821
Matched IDs not found in Source 2 or Source 3: 2206821

In [24]:
print(train_ground_truth["matched_entity_ids"].head(10).to_list())
print(train_ground_truth["matched_entity_ids"].dtype)

value = train_ground_truth.loc[0, "matched_entity_ids"]

print("Raw value:")
print(repr(value))

print("\nSplit result:")
print(value.split(","))

['S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364', 'S2-249013014,S2-197070651,S3-478195123,S3-384364074', 'S2-790675320,S2-479876582,S3-878454467', 'S2-153058913,S2-24659151,S3-679606215', 'S2-478959098,S2-553508714,S2-625774905,S3-728090388,S3-928796641,S3-449308785', 'S2-755677256,S3-187831601,S3-641489370,S3-476250621', 'S2-660036492,S3-804600254', 'S3-274817120,S3-312496301', 'S2-648035184,S3-588502663', 'S2-383871912,S3-74481402,S3-576451439']
str
Raw value:
'S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364'

Split result:
['S2-681193310', 'S2-743505751', 'S3-775321672', 'S3-11291185', 'S3-860443364']

In [25]:
# Split every matched_entity_ids value into individual IDs
matched_lists = (
    train_ground_truth["matched_entity_ids"]
    .fillna("")
    .apply(lambda x: [i.strip() for i in x.split(",") if i.strip()])
)

# Flatten into one Series
matched_ids = matched_lists.explode()

print("Total matched ID references:", len(matched_ids))
print("Unique matched IDs:", matched_ids.nunique())

# Source ID sets
source2_ids = set(train_source2["entity_id"])
source3_ids = set(train_source3["entity_id"])

# Check existence
valid_ids = matched_ids.isin(source2_ids | source3_ids)

print("Matched IDs found in Source 2 or Source 3:", valid_ids.sum())
print("Matched IDs NOT found:", (~valid_ids).sum())

# Check prefixes
valid_prefix = matched_ids.str.startswith(("S2-", "S3-"))

print("Invalid prefixes:", (~valid_prefix).sum())

Total matched ID references: 7761612
Unique matched IDs: 7638365
Matched IDs found in Source 2 or Source 3: 7638365
Matched IDs NOT found: 123247
Invalid prefixes: 123247

In [26]:
duplicate_match_count = sum(
    len(ids) != len(set(ids))
    for ids in matched_lists
)

print("Source 1 records with duplicate matched IDs:", duplicate_match_count)

Source 1 records with duplicate matched IDs: 0

In [27]:
sample_names = train_source2["business_name"].dropna().sample(20, random_state=42)

for name in sample_names:
    print(repr(name))

'Jnsarcsr'
'Heera Poldlechnc'
'PEDIATRIC DENTISTRY CARE ASSOCIATES OF TEMPE INC | www.pediatric.com'
'WALKER AND KELLY (INC.)'
'Chiropractic  Partners'
"Karmen's Láboratories"
'LUNA BEACON SUPPLY, LLC'
'STRATEGIC  PRIME YHN PARTNERS'
'Kudrat Iron Infratech Limited'
'TYAGI AND CHAN GROUP PARTNERS'
'Al Foundation  Private'
'LLC American Hgil'
'Dynamic Reseahr  Corporation PLLC'
'మోడర్న్ సాఫ్ట్\u200cవేర్ ప్రైవేట్ లిమిటెడ్'
'Beck Liberty Nefhld (LLC)'
'Dermatology  Group'
'सिटी कंसल्टिंग प्राइवेट लिमिटेड'
'Kelley Mid Mid Inc Service'
'Kim Cnotineotla Cargo'
'Ironclad Kteoak Inc'

In [28]:
sample_addresses = (
    train_source2["business_address"]
    .dropna()
    .sample(20, random_state=42)
)

for address in sample_addresses:
    print(repr(address))

'GROUND FLOOR, MUMBAI, MUMBAI CITY, Maharashtra'
'650 LYNN AVE, ROMEOVVILLE, IL'
'17/427 MELADOOR MELADOOR P.O, MELADOOR, NULL, Kerala'
'007320 ABRAHAM CT, NEWPORT EWS, VA'
'4350  BRUSHWOOD LAKE RD, PMB 3651, COLUMBIA, MO'
'C-15, MUMBAI (SUBURBAN), MUMBAI CITY, Maharashtra'
'NO 0037 HOUSE OF MANJU DEVI, VILL-HEDAIATPUR, TOLA-MURADPUR, SAIDPUR, BAKHTIARPUR, PATNA, बिहार'
'9657 SCARON DR, SCOTTSDALE AIRPARK, AZ'
'##3011 AVENUE EAST, WILSON, KS'
'938 CANAAN ROED, PITTSFIELD, ME'
'6712 1/2 64TH PLACE, MARYSVILLE, WA'
'322, 03RD FLOOR, SUNCITY SUCCESS TOWER GOLF COURSE EXTENTION ROAD SECTOR 65, GURUGRAM, Haryana'
'HN 535  1/10104, SECOND FLOOR, STREET NO. 3L, WEST GORAKH PARK, SHAHDARA, VIKAS CINEMALL, Delhi'
'301 COLLIER DR, SEVIERVILLE, TN'
'228 FRENCH STREET, WATERTOWN, CT'
'1981 LACEBARK DR, NC, CORNELIUS'
'7501 CHRISTMAS CHOLLA DRIVE, SCOTTSDALE KACHINA, AZ'
'2835 LAROSE AVENUE, MEMPHIS, TN'
'2331 HOLLY SPRING DR, SILVER SPRING, MD'
'2026 RUBY STREET, CHATTANOOGA, TN'

In [29]:
print(train_source2["country"].value_counts())
print()
print(train_source3["country"].value_counts())

country
US       3016817
India    2017799
Name: count, dtype: int64

country
US       3170056
India    2115547
Name: count, dtype: int64

In [44]:
import re
import unicodedata


def normalize_text(text):
    if pd.isna(text):
        return ""

    text = str(text)

    # Unicode normalization
    text = unicodedata.normalize("NFKC", text)

    # Lowercase
    text = text.lower()

    # Remove URL artifacts
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)

    # Replace punctuation/symbols with spaces
    text = "".join(
        char if (
            unicodedata.category(char).startswith(("L", "M", "N"))
            or char.isspace()
        ) else " "
        for char in text
    )
    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [32]:
test_names = [
    "WALKER AND KELLY (INC.)",
    "Karmen's Láboratories",
    "LUNA BEACON SUPPLY, LLC",
    "Dynamic Reseahr  Corporation PLLC",
]

for name in test_names:
    print("Original :", name)
    print("Normalized:", normalize_text(name))
    print()

Original : WALKER AND KELLY (INC.)
Normalized: walker and kelly inc

Original : Karmen's Láboratories
Normalized: karmen s láboratories

Original : LUNA BEACON SUPPLY, LLC
Normalized: luna beacon supply llc

Original : Dynamic Reseahr  Corporation PLLC
Normalized: dynamic reseahr corporation pllc

In [33]:
LEGAL_SUFFIXES = {
    "private limited",
    "pvt ltd",
    "pvt limited",
    "private ltd",
    "limited",
    "ltd",
    "corporation",
    "corp",
    "incorporated",
    "inc",
    "llc",
    "pllc",
    "llp",
}


def normalize_name(name):
    text = normalize_text(name)

    if not text:
        return ""

    # Remove legal suffixes only when they occur at the end
    for suffix in sorted(LEGAL_SUFFIXES, key=len, reverse=True):
        if text.endswith(" " + suffix):
            text = text[:-(len(suffix) + 1)].strip()
            break

    return text

In [34]:
test_names = [
    "WALKER AND KELLY (INC.)",
    "LUNA BEACON SUPPLY, LLC",
    "Dynamic Research Corporation PLLC",
    "Kudrat Iron Infratech Limited",
    "ABC Technologies Pvt Ltd",
    "ABC Technologies Private Limited",
]

for name in test_names:
    print("Original :", name)
    print("Normalized:", normalize_name(name))
    print()

Original : WALKER AND KELLY (INC.)
Normalized: walker and kelly

Original : LUNA BEACON SUPPLY, LLC
Normalized: luna beacon supply

Original : Dynamic Research Corporation PLLC
Normalized: dynamic research corporation

Original : Kudrat Iron Infratech Limited
Normalized: kudrat iron infratech

Original : ABC Technologies Pvt Ltd
Normalized: abc technologies

Original : ABC Technologies Private Limited
Normalized: abc technologies

In [43]:
def normalize_address(address):
    if pd.isna(address):
        return ""

    text = str(address)

    # Unicode normalization
    text = unicodedata.normalize("NFKC", text)

    # Lowercase
    text = text.lower()

    # Remove URL artifacts
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)

    # Replace punctuation with spaces
    text = "".join(
    char if (
        unicodedata.category(char).startswith(("L", "M", "N"))
        or char.isspace()
    ) else " "
    for char in text
)

    # Remove literal missing-value tokens
    text = re.sub(r"\b(null|none|nan)\b", " ", text)

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [38]:
test_addresses = [
    "650 LYNN AVE, ROMEOVVILLE, IL",
    "4350  BRUSHWOOD LAKE RD, PMB 3651, COLUMBIA, MO",
    "17/427 MELADOOR MELADOOR P.O, MELADOOR, NULL, Kerala",
    "##3011 AVENUE EAST, WILSON, KS",
    "322, 03RD FLOOR, SUNCITY SUCCESS TOWER GOLF COURSE EXTENTION ROAD SECTOR 65, GURUGRAM, Haryana",
]

for address in test_addresses:
    print("Original  :", address)
    print("Normalized:", normalize_address(address))
    print()

Original  : 650 LYNN AVE, ROMEOVVILLE, IL
Normalized: 650 lynn ave romeovville il

Original  : 4350  BRUSHWOOD LAKE RD, PMB 3651, COLUMBIA, MO
Normalized: 4350 brushwood lake rd pmb 3651 columbia mo

Original  : 17/427 MELADOOR MELADOOR P.O, MELADOOR, NULL, Kerala
Normalized: 17 427 meladoor meladoor p o meladoor kerala

Original  : ##3011 AVENUE EAST, WILSON, KS
Normalized: 3011 avenue east wilson ks

Original  : 322, 03RD FLOOR, SUNCITY SUCCESS TOWER GOLF COURSE EXTENTION ROAD SECTOR 65, GURUGRAM, Haryana
Normalized: 322 03rd floor suncity success tower golf course extention road sector 65 gurugram haryana

In [39]:
def normalize_country(country):
    if pd.isna(country):
        return ""

    text = unicodedata.normalize("NFKC", str(country))
    text = text.lower().strip()

    return text

In [40]:
test_countries = [
    "US",
    "India",
    "  India  ",
    "US ",
    None
]

for country in test_countries:
    print("Original  :", repr(country))
    print("Normalized:", repr(normalize_country(country)))
    print()

Original  : 'US'
Normalized: 'us'

Original  : 'India'
Normalized: 'india'

Original  : '  India  '
Normalized: 'india'

Original  : 'US '
Normalized: 'us'

Original  : None
Normalized: ''

In [41]:
sample_s1 = train_source1.sample(5, random_state=42)
sample_s2 = train_source2.sample(5, random_state=42)
sample_s3 = train_source3.sample(5, random_state=42)

In [42]:
for df_name, df in [
    ("Source 1", sample_s1),
    ("Source 2", sample_s2),
    ("Source 3", sample_s3)
]:
    print(f"\n===== {df_name} =====")

    for _, row in df.iterrows():
        print("Original name :", row["business_name"])
        print("Normalized     :", normalize_name(row["business_name"]))
        print("Original addr  :", row["business_address"])
        print("Normalized     :", normalize_address(row["business_address"]))
        print("Country        :", normalize_country(row["country"]))
        print("-" * 70)

===== Source 1 =====
Original name : Pediatric Medicine PLLC
Normalized     : pediatric medicine
Original addr  : 4850 20, Otisco, NY
Normalized     : 4850 20 otisco ny
Country        : us
----------------------------------------------------------------------
Original name : Fetech National Twin
Normalized     : fetech national twin
Original addr  : 19034 Woodburn Road, Woodburn, IN
Normalized     : 19034 woodburn road woodburn in
Country        : us
----------------------------------------------------------------------
Original name : General Design Innovations LLC
Normalized     : general design innovations
Original addr  : 7241 Osage Avenue, Mesa, AZ
Normalized     : 7241 osage avenue mesa az
Country        : us
----------------------------------------------------------------------
Original name : Construction Ideaz Papers Private Limited
Normalized     : construction ideaz papers
Original addr  : Building No.4/606, Prabhul Cottage Karimbalur, Elakamon, Ayiroor P.O., Thiruvananthapuram, Trivandrum, Kerala
Normalized     : building no 4 606 prabhul cottage karimbalur elakamon ayiroor p o thiruvananthapuram trivandrum kerala
Country        : india
----------------------------------------------------------------------
Original name : Penaloza and Bittle First Inc.
Normalized     : penaloza and bittle first
Original addr  : 4255 Charleswood Avenue, Memphis, TN
Normalized     : 4255 charleswood avenue memphis tn
Country        : us
----------------------------------------------------------------------

===== Source 2 =====
Original name : Harbor  Center
Normalized     : harbor center
Original addr  : 6309 EVANGELINE TRAIL, AUSTIN, TX
Normalized     : 6309 evangeline trail austin tx
Country        : us
----------------------------------------------------------------------
Original name : STEWARD ACE PREMIER
Normalized     : steward ace premier
Original addr  : 1029 MAPLE HILL RD, LEBANON, TN
Normalized     : 1029 maple hill rd lebanon tn
Country        : us
----------------------------------------------------------------------
Original name : Klapper and Lott
Normalized     : klapper and lott
Original addr  : 368 VINE STREET, TOOELE, UT
Normalized     : 368 vine street tooele ut
Country        : us
----------------------------------------------------------------------
Original name : EAR NOSE & THROAT CARE
Normalized     : ear nose throat care
Original addr  : YORK RD, LUTHERVILLE, MD
Normalized     : york rd lutherville md
Country        : us
----------------------------------------------------------------------
Original name : Shield Inrfabuild Private Limited
Normalized     : shield inrfabuild
Original addr  : 206 FLAT NO. LG 1 KH NO. 514, 516 SHYAM BHAWAN JHANDA COLONY FATEHPUR, DELHI, Delhi
Normalized     : 206 flat no lg 1 kh no 514 516 shyam bhawan jhanda colony fatehpur delhi delhi
Country        : india
----------------------------------------------------------------------

===== Source 3 =====
Original name : Dr Apex Pvt Ltd Partners
Normalized     : dr apex pvt ltd partners
Original addr  : 75 Tulshibaugwale Colonysahakarnagar, Pune, MH
Normalized     : 75 tulshibaugwale colonysahakarnagar pune mh
Country        : india
----------------------------------------------------------------------
Original name : Shiva  Mines Pvt Ltd
Normalized     : shiva mines
Original addr  : F-17, Sector 22, Noida, Gautam Buddha Nagar, उत्तर प्रदेश
Normalized     : f 17 sector 22 noida gautam buddha nagar उत तर प रद श
Country        : india
----------------------------------------------------------------------
Original name : Vanguard Métropolitan Sunshine
Normalized     : vanguard métropolitan sunshine
Original addr  : 3518-B Crestview Ln, Catoosa, Oklahoma
Normalized     : 3518 b crestview ln catoosa oklahoma
Country        : us
----------------------------------------------------------------------
Original name : Vanguard Apoge-Inc
Normalized     : vanguard apoge
Original addr  : 2150 350, Greencastle, Indiana
Normalized     : 2150 350 greencastle indiana
Country        : us
----------------------------------------------------------------------
Original name : रियल एग्रो प्राइवेट लिमिटेड
Normalized     : र यल एग र प र इव ट ल म ट ड
Original addr  : H.no 829 D-225vivek Vihar, Delhi, दिल्ली
Normalized     : h no 829 d 225vivek vihar delhi द ल ल
Country        : india
----------------------------------------------------------------------

In [45]:
test = "H.no 829 D-225vivek Vihar, Delhi, दिल्ली"

print("Original  :", test)
print("Normalized:", normalize_address(test))

Original  : H.no 829 D-225vivek Vihar, Delhi, दिल्ली
Normalized: h no 829 d 225vivek vihar delhi दिल्ली

In [51]:
from business_entity_resolution.preprocessing import (
    normalize_text,
    normalize_name,
    normalize_address,
    normalize_country,
)

In [48]:
import os
print(os.getcwd())

d:\amazon-ml-2026-entity-resolution\notebooks

In [52]:
print(normalize_name("ABC Technologies Private Limited"))
print(normalize_name("WALKER AND KELLY (INC.)"))
print(normalize_address("17/427 MELADOOR, NULL, Kerala"))
print(normalize_address("H.no 829 D-225vivek Vihar, Delhi, दिल्ली"))
print(normalize_country("  India  "))

abc technologies
walker and kelly
17 427 meladoor kerala
h no 829 d 225vivek vihar delhi दिल्ली
india